// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_gsdBrwQUQQZ18pylK2grdsLQYO8xJFM',
    appId: '1:614084020934:web:cb1e239cdcaaaa415725c7',
    messagingSenderId: '614084020934',
    projectId: 'flutter-4a580',
    authDomain: 'flutter-4a580.firebaseapp.com',
    storageBucket: 'flutter-4a580.firebasestorage.app',
    measurementId: 'G-XCFPPMVGFC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsjmvliEcgP4JaelLdAIpn3oAoG-BKXxQ',
    appId: '1:614084020934:android:7b5abe92a3e6aad95725c7',
    messagingSenderId: '614084020934',
    projectId: 'flutter-4a580',
    storageBucket: 'flutter-4a580.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhw_8_q74xatExrmhfE6jxgdTxmAgmIDw',
    appId: '1:614084020934:ios:079ecd7e4aa0d7505725c7',
    messagingSenderId: '614084020934',
    projectId: 'flutter-4a580',
    storageBucket: 'flutter-4a580.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhw_8_q74xatExrmhfE6jxgdTxmAgmIDw',
    appId: '1:614084020934:ios:079ecd7e4aa0d7505725c7',
    messagingSenderId: '614084020934',
    projectId: 'flutter-4a580',
    storageBucket: 'flutter-4a580.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_gsdBrwQUQQZ18pylK2grdsLQYO8xJFM',
    appId: '1:614084020934:web:255767d73e9ec7de5725c7',
    messagingSenderId: '614084020934',
    projectId: 'flutter-4a580',
    authDomain: 'flutter-4a580.firebaseapp.com',
    storageBucket: 'flutter-4a580.firebasestorage.app',
    measurementId: 'G-G61L8WP4VK',
  );
}
